int beat = 375;
int half = 750;
int whole = 1500;

play(C4, beat);
play(C4, beat / 2);
play(D4, beat);
play(C4, beat);
play(F4, beat);
play(E4, half);

play(C4, beat);
play(C4, beat / 2);
play(D4, beat);
play(C4, beat);
play(G4, beat);
play(F4, half);

play(C4, beat);
play(C4, beat / 2);
play(C5, beat);
play(A4, beat);
play(F4, beat);
play(E4, beat);
play(D4, half);

play(Bb4, beat);
play(Bb4, beat / 2);
play(A4, beat);
play(F4, beat);
play(G4, beat);
play(F4, half);